sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: g9+GgmDr5+W9XsTgKvRHBWMi7xegmKnhiaXKbmBzg1/kW6huq7LrB8RoNSl+Q2msQmcTgwy6Eykx2mFq7oI1C26nz9Y2SblnjIrbHrqq6rM94KRO4n1X0zKQSUlBac2k25SINicAjvEvZ8VVr1l4k2oAIHlNM4gUQQytSsMiaOovCSqWKOi1x+tcI4HpsO2vCH/B+n3R3sJMZ6uwdGC85VIpDqg6e1NqzwHZ41jPma332co/ZAB4xjlsEFp1RkecUSnXP7XpFF6uqwU+ym0DW1B786cUmnxBmJmsdhOEX+nu9rObA4Gd9UmY0SvmznXWR4exxvrgU9qSpQ99eJJx3X+G26Jh40OXd7yVp9LUIdKfPSVA3C36XMxOW/ULuQI+FVt8JnwHF12c2wndgj6UREDyRTQ0AVfwwOF9wUJz+9EVkHFAM/1kFUhaEZg0nb4WigWlj9yHyUNExqsVYh/iuefEv/jh/t8BC6CaMaROk08ipTH6NHiwOw6VLVFUyZ3ZSI2Kmj7N0VS2cULlh0VCBDBBpPEzNZDOVHdJsdiCpU2E+gdTljADxxEEkmIxX1XPtWASwHE++Ao2bDEXJ/5R+NQs8bPHvu7F0j77cFWa24hgQUNTYg7wwZNd5gdlQ5xk0yacQeRQUoCrPegetJ+poSvIsiHPTchQfs73JUpMFNY=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Emma-McChesney-and-Co._453
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy